# -*- coding: utf-8 -*-
"""01_EDA_Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r8ApcLgDd_Lnrzmmfzjnwgp59TOpP0Cr

#  Notebook 1: EDA & Preprocessing
## Credit Risk Assessment System — FinTech Solutions Inc.

**Objective:** Explore and preprocess the German Credit Risk dataset to prepare clean, feature-engineered data for model training.

## 0. Drive Mounted
"""

from google.colab import drive
drive.mount('/content/drive')

import os
BASE = '/content/drive/MyDrive/T2_Project_Siddharth_Agarwal'
os.makedirs(f'{BASE}/Models', exist_ok=True)
os.makedirs(f'{BASE}/Data',   exist_ok=True)
os.makedirs(f'{BASE}/Visualizations', exist_ok=True)
os.makedirs(f'{BASE}/Report', exist_ok=True)
print('Drive mounted and folders created.')

"""
##  1. Environment Setup & Library Installation"""

# Install required libraries
!pip install -q pandas numpy matplotlib seaborn scikit-learn xgboost mlflow

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

print('Libraries loaded successfully')

"""##  2. Data Loading & Inspection"""

# ── Load dataset ──
DATA_PATH = "/content/drive/MyDrive/T2_Project_Siddharth_Agarwal/Data/german_credit_data.csv"
df = pd.read_csv(DATA_PATH)
print('Dataset loaded from file.')


print(f'Shape: {df.shape}')
df.head()

# ── Data types & summary statistics ──
print('=== Data Types ===')
print(df.dtypes)
print('\n=== Summary Statistics ===')
df.describe(include='all')

# ── Missing values & duplicates ──
print('=== Missing Values ===')
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_df = pd.DataFrame({'Missing Count': missing, 'Missing %': missing_pct})
print(missing_df[missing_df['Missing Count'] > 0])

print(f'\n=== Duplicate Rows ===')
print(f'Duplicate count: {df.duplicated().sum()}')

"""## 3. Exploratory Data Analysis (EDA)"""

# ── 3.1 Target Distribution ──
fig, ax = plt.subplots(figsize=(7, 4))
counts = df['Risk'].value_counts()
sns.countplot(x='Risk', data=df, palette=['#2ecc71','#e74c3c'], ax=ax)
for p in ax.patches:
    ax.annotate(f'{int(p.get_height())} ({p.get_height()/len(df)*100:.1f}%)',
                (p.get_x() + p.get_width()/2., p.get_height()),
                ha='center', va='bottom', fontsize=11)
ax.set_title('Distribution of Credit Risk (Target Variable)', fontsize=14, fontweight='bold')
ax.set_xlabel('Risk Category')
ax.set_ylabel('Count')
plt.tight_layout()
plt.savefig(f'{BASE}/Visualizations/target_distribution.png', dpi=150)
plt.show()
print(f'Class imbalance ratio (bad:good) = {counts["bad"]/counts["good"]:.2f}')

# ── 3.2 Histograms: Age, Credit Amount, Duration ──
plot_df = df.reset_index() if 'Age' not in df.columns else df

num_cols = ['Age', 'Credit amount', 'Duration']
fig, axes = plt.subplots(1, 3, figsize=(16, 4))
colors = ['blue', 'purple', 'orange']

for ax, col, color in zip(axes, num_cols, colors):
    ax.hist(plot_df[col], bins=30, color=color, edgecolor='white', alpha=0.85)
    ax.set_title(f'Distribution of {col}', fontweight='bold')
    ax.set_xlabel(col)
    ax.set_ylabel('Frequency')
    ax.axvline(plot_df[col].mean(), color='red', linestyle='--', label=f'Mean: {plot_df[col].mean():.1f}')
    ax.legend(fontsize=9)

plt.suptitle('Histograms of Key Numerical Features', fontsize=13, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig(f'{BASE}/Visualizations/histograms.png', dpi=150)
plt.show()

# ── 3.3 Box Plots: Numerical Features by Risk ──

plot_df = df.reset_index() if 'Age' not in df.columns else df

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
for ax, col in zip(axes, num_cols):
    plot_df.boxplot(column=col, by='Risk', ax=ax,
               boxprops=dict(color='#2c3e50'),
               medianprops=dict(color='red', linewidth=2))
    ax.set_title(f'{col} by Risk', fontweight='bold')
    ax.set_xlabel('Risk Category')
plt.suptitle('Box Plots of Numerical Features Grouped by Risk', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig(f'{BASE}/Visualizations/boxplots.png', dpi=150)
plt.show()

# ── 3.4 Correlation Heatmap ──
df_temp = df.reset_index() if 'Age' not in df.columns else df.copy()
df_temp['Risk_enc'] = (df_temp['Risk'] == 'bad').astype(int)
corr_cols = ['Age', 'Credit amount', 'Duration', 'Job', 'Risk_enc']
corr = df_temp[corr_cols].corr()

fig, ax = plt.subplots(figsize=(7, 5))
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, annot=True, fmt='.2f', cmap='RdYlGn', ax=ax,
            mask=mask, linewidths=0.5, center=0,
            annot_kws={'size': 11})
ax.set_title('Correlation Heatmap', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig(f'{BASE}/Visualizations/correlation_heatmap.png', dpi=150)
plt.show()

# ── 3.5 Default Rate by Purpose ──
purpose_risk = df.groupby('Purpose')['Risk'].apply(
    lambda x: (x == 'bad').mean() * 100).sort_values(ascending=False).reset_index()
purpose_risk.columns = ['Purpose', 'Default Rate (%)']

fig, ax = plt.subplots(figsize=(10, 5))
bars = ax.barh(purpose_risk['Purpose'], purpose_risk['Default Rate (%)'],
               color=plt.cm.RdYlGn_r(np.linspace(0.1, 0.9, len(purpose_risk))))
ax.set_xlabel('Default Rate (%)', fontsize=11)
ax.set_title('Default Rate by Loan Purpose', fontsize=14, fontweight='bold')
for bar, val in zip(bars, purpose_risk['Default Rate (%)']):
    ax.text(bar.get_width() + 0.3, bar.get_y() + bar.get_height()/2,
            f'{val:.1f}%', va='center', fontsize=9)
plt.tight_layout()
plt.savefig(f'{BASE}/Visualizations/default_by_purpose.png', dpi=150)
plt.show()

# ── 3.6 Age Group vs Risk ──
df_temp2 = df.reset_index()

df_temp2['Age_Group'] = pd.cut(df_temp2['Age'],
    bins=[18, 25, 35, 50, 75],
    labels=['18-25', '26-35', '36-50', '51+'])

age_risk = df_temp2.groupby(['Age_Group', 'Risk']).size().unstack(fill_value=0)
age_risk_pct = age_risk.div(age_risk.sum(axis=1), axis=0) * 100

fig, ax = plt.subplots(figsize=(8, 5))
age_risk_pct.plot(kind='bar', ax=ax, color=['#2ecc71','#e74c3c'],
                  edgecolor='white', width=0.6)
ax.set_title('Risk Distribution by Age Group', fontsize=14, fontweight='bold')
ax.set_xlabel('Age Group')
ax.set_ylabel('Percentage (%)')
ax.legend(['Good', 'Bad'], title='Risk')
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig(f'{BASE}/Visualizations/age_group_risk.png', dpi=150)
plt.show()

"""##  4. Data Preprocessing

### Missing Value Strategy

**Saving accounts (20% missing):** Missing likely indicates no savings account. We impute with 'none' , a meaningful category rather than a random value. This preserves the information that these customers lack savings.

**Checking account (26% missing):** Similarly, missing implies no checking account. We impute with 'none'. This is a valid financial state and prevents data leakage from statistical imputation.

"""

# ── 4.1 Missing Value Imputation ──
df['Saving accounts'] = df['Saving accounts'].fillna('none')
df['Checking account'] = df['Checking account'].fillna('none')

print('Missing values after imputation:')
print(df.isnull().sum())
print('\n All missing values resolved.')

# ── 4.2 Encode Target Variable ──
df['Risk'] = df['Risk'].map({'good': 0, 'bad': 1})
print('Target encoding:')
print(df['Risk'].value_counts())

# ── 4.3 Feature Engineering ──

# Move 'Age' from index back to column so it can be used for calculations
if 'Age' not in df.columns:
    df = df.reset_index()

# Feature 1: Credit-to-Duration Ratio
df['Credit_to_Duration_Ratio'] = df['Credit amount'] / df['Duration']

# Feature 2: Age Group (Bucketed Ordinal)
# Adjusted bins to [18, 75] and used include_lowest=True to avoid NaNs at boundaries
df['Age_Group'] = pd.cut(df['Age'],
    bins=[0, 25, 35, 50, 100],
    labels=[0, 1, 2, 3],
    include_lowest=True).astype('Int64')

# Feature 3: High_Risk_Purpose (Binary Flag)
high_risk_purposes = ['vacation/others', 'education', 'repairs']
df['High_Risk_Purpose'] = df['Purpose'].isin(high_risk_purposes).astype(int)

# Feature 4: Account_Stability Score
account_map = {'none': 0, 'little': 1, 'moderate': 2, 'quite rich': 3, 'rich': 4}
df['Account_Stability'] = (
    df['Saving accounts'].map(account_map).fillna(0) +
    df['Checking account'].map(account_map).fillna(0)
)

print('4 engineered features created:')
print(df[['Credit_to_Duration_Ratio','Age_Group','High_Risk_Purpose','Account_Stability']].head())

# ── 4.4 Encoding Categorical Variables ──
cat_cols = ['Sex', 'Housing', 'Saving accounts', 'Checking account', 'Purpose']
df_encoded = pd.get_dummies(df, columns=cat_cols, drop_first=True)
print(f'Shape after encoding: {df_encoded.shape}')
print(df_encoded.dtypes.value_counts())

# ── 4.5 Train-Test Split ──
X = df_encoded.drop('Risk', axis=1)
y = df_encoded['Risk']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

print(f'Train size: {X_train.shape[0]} | Test size: {X_test.shape[0]}')
print(f'Train class balance: {y_train.value_counts().to_dict()}')
print(f'Test class balance:  {y_test.value_counts().to_dict()}')

# ── 4.6 Standardize Numerical Features ──
num_features = ['Age', 'Credit amount', 'Duration', 'Job',
                'Credit_to_Duration_Ratio', 'Account_Stability']
# Only scale columns that exist
num_features = [c for c in num_features if c in X_train.columns]

scaler = StandardScaler()
X_train[num_features] = scaler.fit_transform(X_train[num_features])
X_test[num_features]  = scaler.transform(X_test[num_features])

print('Numerical features standardized.')
X_train[num_features].describe().round(2)

# ── 4.7 Save Preprocessed Data to Google Drive ──
import joblib

X_train.to_csv(f'{BASE}/Data/X_train.csv', index=False)
X_test.to_csv( f'{BASE}/Data/X_test.csv',  index=False)
y_train.to_csv(f'{BASE}/Data/y_train.csv', index=False)
y_test.to_csv( f'{BASE}/Data/y_test.csv',  index=False)
joblib.dump(scaler, f'{BASE}/Models/scaler.pkl')

print('All data and scaler saved to Drive.')
print(f'Final feature count: {X_train.shape[1]}')

"""## Notebook 1 Summary

| Step | Outcome |
|------|----------|
| Dataset shape | 1000 rows × 10 features |
| Missing values | Imputed `Saving accounts` & `Checking account` with `'none'` |
| Encoding | One-Hot Encoding for 5 categorical features |
| Feature Engineering | 4 new features created |
| Train/Test Split | 80%/20%, stratified, random_state=42 |
| Scaling | StandardScaler on numerical features |

**Next:** Proceed to Notebook 2 for model training.
"""