# -*- coding: utf-8 -*-
"""02_Model_Development.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gEqpwubR3dyCjKHZxDHNrfpSoN7uS9E7

# Notebook 2: Model Development
## Credit Risk Assessment System — FinTech Solutions Inc.

**Objective:** Train 4 classifiers, tune 2 of them, and track all experiments with MLflow.

## 0. Drive Mounted
"""

from google.colab import drive
drive.mount('/content/drive')

import os
BASE = '/content/drive/MyDrive/T2_Project_Siddharth_Agarwal'
print('Drive mounted.')

"""##  1. Setup & Data Loading"""

!pip install -q mlflow xgboost scikit-learn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import mlflow
import mlflow.sklearn
import pickle
import warnings
warnings.filterwarnings('ignore')

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import (
    cross_val_score, GridSearchCV, RandomizedSearchCV, StratifiedKFold
)
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix, classification_report
)

print('Libraries loaded')

import pandas as pd

X_train = pd.read_csv(f'{BASE}/Data/X_train.csv')
X_test  = pd.read_csv(f'{BASE}/Data/X_test.csv')
y_train = pd.read_csv(f'{BASE}/Data/y_train.csv').squeeze()
y_test  = pd.read_csv(f'{BASE}/Data/y_test.csv').squeeze()

print(f'Data loaded — Train: {X_train.shape}, Test: {X_test.shape}')

"""##  2. MLflow Setup"""

# ── Configure MLflow ──
mlflow.set_experiment('credit_risk_classification')
print(f' MLflow experiment set: credit_risk_classification')

# Helper: compute all metrics
def compute_metrics(model, X, y):
    """Return dict of classification metrics."""
    y_pred = model.predict(X)
    return {
        'accuracy':  round(accuracy_score(y, y_pred), 4),
        'precision': round(precision_score(y, y_pred, zero_division=0), 4),
        'recall':    round(recall_score(y, y_pred), 4),
        'f1':        round(f1_score(y, y_pred), 4),
    }

#  Helper: log run to MLflow
def log_mlflow_run(run_name, model, params, metrics, X_test, y_test):
    """Log model, params, metrics, and confusion matrix to MLflow."""
    with mlflow.start_run(run_name=run_name):
        mlflow.log_params(params)
        mlflow.log_metrics(metrics)
        mlflow.sklearn.log_model(model, 'model')

        # Save and log confusion matrix as artifact
        y_pred = model.predict(X_test)
        cm = confusion_matrix(y_test, y_pred)
        fig, ax = plt.subplots(figsize=(5, 4))
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax,
                    xticklabels=['Good','Bad'], yticklabels=['Good','Bad'])
        ax.set_title(f'Confusion Matrix — {run_name}')
        ax.set_ylabel('Actual')
        ax.set_xlabel('Predicted')
        cm_path = f'{BASE}/Visualizations/cm_{run_name.replace(" ","_")}.png'
        plt.tight_layout()
        plt.savefig(cm_path, dpi=120)
        plt.close()
        mlflow.log_artifact(cm_path)
    print(f'Logged: {run_name} | Recall={metrics["recall"]} | F1={metrics["f1"]}')

#  CV helper
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
results = {}

"""##  3. Model 1: Logistic Regression (Baseline Pipeline)"""

# ── Logistic Regression via Pipeline ──
lr_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('clf', LogisticRegression(
        class_weight='balanced',  # handles class imbalance
        max_iter=1000,
        random_state=42
    ))
])

lr_pipeline.fit(X_train, y_train)

# CV score
lr_cv = cross_val_score(lr_pipeline, X_train, y_train, cv=cv, scoring='recall').mean()
lr_metrics = compute_metrics(lr_pipeline, X_test, y_test)
results['Logistic Regression'] = lr_metrics

print(f'Logistic Regression — CV Recall: {lr_cv:.4f}')
print(f'Test Metrics: {lr_metrics}')

# Log to MLflow
log_mlflow_run(
    run_name='Logistic Regression Baseline',
    model=lr_pipeline,
    params={'model': 'LogisticRegression', 'class_weight': 'balanced', 'max_iter': 1000},
    metrics=lr_metrics,
    X_test=X_test, y_test=y_test
)

"""##  4. Model 2: Decision Tree"""

# ── Decision Tree ──
dt_model = DecisionTreeClassifier(
    class_weight='balanced',
    random_state=42,
    max_depth=6
)
dt_model.fit(X_train, y_train)

dt_cv = cross_val_score(dt_model, X_train, y_train, cv=cv, scoring='recall').mean()
dt_metrics = compute_metrics(dt_model, X_test, y_test)
results['Decision Tree'] = dt_metrics

print(f'Decision Tree — CV Recall: {dt_cv:.4f}')
print(f'Test Metrics: {dt_metrics}')

log_mlflow_run(
    run_name='Decision Tree Baseline',
    model=dt_model,
    params={'model': 'DecisionTree', 'max_depth': 6, 'class_weight': 'balanced'},
    metrics=dt_metrics,
    X_test=X_test, y_test=y_test
)

"""##  5. Model 3: Random Forest"""

# ── Random Forest ──
rf_model = RandomForestClassifier(
    n_estimators=200,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)
rf_model.fit(X_train, y_train)

rf_cv = cross_val_score(rf_model, X_train, y_train, cv=cv, scoring='recall').mean()
rf_metrics = compute_metrics(rf_model, X_test, y_test)
results['Random Forest'] = rf_metrics

print(f'Random Forest — CV Recall: {rf_cv:.4f}')
print(f'Test Metrics: {rf_metrics}')

log_mlflow_run(
    run_name='Random Forest Baseline',
    model=rf_model,
    params={'model': 'RandomForest', 'n_estimators': 200, 'class_weight': 'balanced'},
    metrics=rf_metrics,
    X_test=X_test, y_test=y_test
)

"""##  6. Model 4: XGBoost"""

# ── XGBoost ──
# Compute scale_pos_weight to handle imbalance
neg_pos_ratio = (y_train == 0).sum() / (y_train == 1).sum()
print(f'scale_pos_weight = {neg_pos_ratio:.2f}')

xgb_model = XGBClassifier(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=5,
    scale_pos_weight=neg_pos_ratio,
    use_label_encoder=False,
    eval_metric='logloss',
    random_state=42,
    n_jobs=-1
)
xgb_model.fit(X_train, y_train)

xgb_cv = cross_val_score(xgb_model, X_train, y_train, cv=cv, scoring='recall').mean()
xgb_metrics = compute_metrics(xgb_model, X_test, y_test)
results['XGBoost'] = xgb_metrics

print(f'XGBoost — CV Recall: {xgb_cv:.4f}')
print(f'Test Metrics: {xgb_metrics}')

log_mlflow_run(
    run_name='XGBoost Baseline',
    model=xgb_model,
    params={'model': 'XGBoost', 'n_estimators': 200, 'learning_rate': 0.1,
            'max_depth': 5, 'scale_pos_weight': round(neg_pos_ratio, 2)},
    metrics=xgb_metrics,
    X_test=X_test, y_test=y_test
)

"""##  7. Hyperparameter Tuning

### Tuning Strategy
We tune **Random Forest** (GridSearchCV) and **XGBoost** (RandomizedSearchCV), as they showed the most promise in baseline evaluation. Primary optimization target is **Recall** to minimize missed defaults, which are the costliest errors in credit risk.

We use 5-fold stratified cross-validation to ensure fair evaluation across imbalanced classes.
"""

# ─────────────────────────────────────────
# 7.1 Tune Random Forest — GridSearchCV
# ─────────────────────────────────────────
rf_param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

print(' Tuning Random Forest (GridSearchCV)...')
rf_grid = GridSearchCV(
    RandomForestClassifier(class_weight='balanced', random_state=42, n_jobs=-1),
    param_grid=rf_param_grid,
    cv=cv,
    scoring='recall',
    n_jobs=-1,
    verbose=0
)
rf_grid.fit(X_train, y_train)

rf_best = rf_grid.best_estimator_
rf_tuned_cv = rf_grid.best_score_
rf_tuned_metrics = compute_metrics(rf_best, X_test, y_test)
results['Random Forest (Tuned)'] = rf_tuned_metrics

print(f'Best Params: {rf_grid.best_params_}')
print(f'Best CV Recall: {rf_tuned_cv:.4f}')
print(f'Test Metrics: {rf_tuned_metrics}')

log_mlflow_run(
    run_name='Random Forest Tuned',
    model=rf_best,
    params=rf_grid.best_params_,
    metrics=rf_tuned_metrics,
    X_test=X_test, y_test=y_test
)

# ─────────────────────────────────────────
# 7.2 Tune XGBoost — RandomizedSearchCV
# ─────────────────────────────────────────
from scipy.stats import randint, uniform

xgb_param_dist = {
    'n_estimators': randint(100, 500),
    'max_depth': randint(3, 10),
    'learning_rate': uniform(0.01, 0.3),
    'subsample': uniform(0.6, 0.4),
    'colsample_bytree': uniform(0.6, 0.4),
    'min_child_weight': randint(1, 10),
    'gamma': uniform(0, 0.5)
}

print('Tuning XGBoost (RandomizedSearchCV, 30 iterations)...')
xgb_rand = RandomizedSearchCV(
    XGBClassifier(
        scale_pos_weight=neg_pos_ratio,
        use_label_encoder=False,
        eval_metric='logloss',
        random_state=42,
        n_jobs=-1
    ),
    param_distributions=xgb_param_dist,
    n_iter=30,
    cv=cv,
    scoring='recall',
    random_state=42,
    n_jobs=-1,
    verbose=0
)
xgb_rand.fit(X_train, y_train)

xgb_best = xgb_rand.best_estimator_
xgb_tuned_cv = xgb_rand.best_score_
xgb_tuned_metrics = compute_metrics(xgb_best, X_test, y_test)
results['XGBoost (Tuned)'] = xgb_tuned_metrics

print(f'Best Params: {xgb_rand.best_params_}')
print(f'Best CV Recall: {xgb_tuned_cv:.4f}')
print(f'Test Metrics: {xgb_tuned_metrics}')

log_mlflow_run(
    run_name='XGBoost Tuned',
    model=xgb_best,
    params=xgb_rand.best_params_,
    metrics=xgb_tuned_metrics,
    X_test=X_test, y_test=y_test
)

"""###  Before vs. After Tuning Comparison

| Model | Before (Recall) | After (Recall) | Improvement |
|-------|----------------|----------------|-------------|
| Random Forest | Baseline CV | Best CV | GridSearchCV |
| XGBoost | Baseline CV | Best CV | RandomizedSearchCV |

**Key takeaways:**
- Tuning focuses on **Recall** since missing a real defaulter costs far more than a false alarm.
- class_weight='balanced' and scale_pos_weight are critical for imbalanced credit data.
- RandomizedSearchCV is preferred for XGBoost due to its larger hyperparameter space.
"""

# ── Comparison Table ──
results_df = pd.DataFrame(results).T
results_df.index.name = 'Model'
results_df = results_df.sort_values('recall', ascending=False)
print('\n=== All Models Performance Summary ===')
print(results_df.to_string())

# ── Save All Models to Google Drive ──
import joblib

models_dict = {
    'Logistic Regression':   lr_pipeline,
    'Decision Tree':         dt_model,
    'Random Forest':         rf_model,
    'Random Forest (Tuned)': rf_best,
    'XGBoost':               xgb_model,
    'XGBoost (Tuned)':       xgb_best
}

joblib.dump(lr_pipeline,  f'{BASE}/Models/logistic_regression.pkl')
joblib.dump(dt_model,     f'{BASE}/Models/decision_tree.pkl')
joblib.dump(rf_model,     f'{BASE}/Models/random_forest.pkl')
joblib.dump(rf_best,      f'{BASE}/Models/random_forest_tuned.pkl')
joblib.dump(xgb_model,    f'{BASE}/Models/xgboost.pkl')
joblib.dump(xgb_best,     f'{BASE}/Models/xgboost_tuned.pkl')
joblib.dump(models_dict,  f'{BASE}/Models/all_models.pkl')

print('All models saved to Drive.')
print(f'Saved models: {list(models_dict.keys())}')

"""## ✅ Notebook 2 Summary

| Model | Trained | Tuned | MLflow Logged |
|-------|---------|-------|---------------|
| Logistic Regression | ✅ | — | ✅ |
| Decision Tree | ✅ | — | ✅ |
| Random Forest | ✅ | ✅ GridSearchCV | ✅ |
| XGBoost | ✅ | ✅ RandomizedSearchCV | ✅ |

**Next:** Proceed to Notebook 3 for full evaluation and deployment planning.
"""